import { ArrowUpRight, Check, ChevronDown, MapPin, MessageCircle, Phone, ShieldCheck, Star } from "lucide-react";

declare global {
  interface Window {
    dataLayer?: Array<Record<string, unknown>>;
  }
}

const whatsappUrl = "https://wa.me/554196592624?text=Ol%C3%A1!%20Vim%20pelo%20site%20da%20Vita%20Sorriso%20e%20gostaria%20de%20agendar%20uma%20avalia%C3%A7%C3%A3o%20para%20implantes%20dent%C3%A1rios%20em%20Curitiba.";
const mapsUrl = "https://www.google.com/maps/dir/?api=1&destination=Rua+Jos%C3%A9+Loureiro%2C+268+-+Centro%2C+Curitiba+-+PR";
const googleReviewsUrl = "https://share.google/MBbblhi456zfs7PGU";

function trackConversion(event: string, placement: string) {
  window.dispatchEvent(new CustomEvent("conversion_click", { detail: { event, placement } }));
  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({ event, cta_placement: placement });
}

function Logo() {
  return <a href="#inicio" aria-label="Vita Sorriso - início"><img src="/assets/vita-logo-red.png" alt="Vita Sorriso Implantes" className="brand-logo" /></a>;
}

function WhatsAppIcon({ size = 21 }: { size?: number }) {
  return <svg className="whatsapp-inline-icon" width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.1-.471-.149-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.521.149-.174.198-.298.298-.497.1-.198.05-.372-.025-.521-.075-.149-.669-1.611-.916-2.206-.242-.579-.487-.5-.669-.51l-.57-.01c-.198 0-.52.074-.793.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.71.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414-.074-.124-.272-.198-.57-.347ZM12.004 2a9.94 9.94 0 0 0-8.48 15.12L2 22l5.02-1.507A9.94 9.94 0 1 0 12.004 2Zm0 18.2a8.24 8.24 0 0 1-4.2-1.15l-.3-.18-2.98.895.915-2.905-.195-.31A8.24 8.24 0 1 1 12.004 20.2Z" /></svg>;
}

function WhatsAppButton({ compact = false, placement = "cta" }: { compact?: boolean; placement?: string }) {
  return <a href={whatsappUrl} target="_blank" rel="noreferrer" className={`whatsapp-button ${compact ? "px-5 py-3 text-sm" : "px-6 py-4"}`} onClick={() => trackConversion("whatsapp_lead", placement)}><WhatsAppIcon size={compact ? 22 : 21} /><span>{compact ? "Agendar avaliação" : "Agendar avaliação pelo WhatsApp"}</span>{!compact && <ArrowUpRight size={16} />}</a>;
}

const faqs = [
  ["Posso colocar dentes fixos rapidamente?", "Em alguns casos, pode ser indicada uma prótese fixa provisória em curto prazo. Isso depende da avaliação clínica e da estabilidade dos implantes."],
  ["Como saber o valor do tratamento?", "O valor depende do seu caso, do número de implantes e do tipo de prótese. Você recebe um plano explicado após a avaliação."],
  ["O tratamento dói?", "O procedimento é realizado com anestesia e os recursos de conforto indicados para cada paciente. Nossa equipe acompanha o pós-operatório."],
];

export default function Home() {
  return <div className="min-h-screen overflow-x-hidden bg-paper text-ink">
    <div className="topline"><span className="topline-dot" /> Implantes dentários em Curitiba <span className="hidden sm:inline">· Segunda a sexta, 8h às 18h</span></div>
    <header className="simple-header"><div className="container flex min-h-[74px] items-center justify-between gap-5"><Logo /><nav className="header-nav" aria-label="Atalhos da página"><a href="#processo">Como funciona</a><a href="#depoimentos">Depoimentos</a><a href="#duvidas">Dúvidas</a><a href="#localizacao">Localização</a></nav><WhatsAppButton compact placement="header" /></div></header>

    <main>
      <section id="inicio" className="ppc-hero hero-section"><div className="hero-orb hero-orb-one" /><div className="container relative grid items-center gap-9 py-12 sm:py-16 lg:grid-cols-[0.98fr_1.02fr] lg:gap-12 lg:py-12"><div className="relative z-10 max-w-[560px] animate-fade-up"><div className="eyebrow">Clínica de implantes em Curitiba</div><h1 className="mt-6 font-display text-[3.25rem] leading-[0.97] tracking-[-0.05em] sm:text-[4rem] lg:text-[4.15rem]">Implantes dentários em Curitiba para voltar a sorrir com <em className="text-gold">segurança.</em></h1><p className="mt-5 max-w-[500px] text-[1rem] leading-7 text-ink/65">Fale com a Vita Sorriso, entenda as possibilidades para o seu caso e agende uma avaliação individual.</p><div className="mt-7 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><WhatsAppButton placement="hero" /><span className="flex items-center gap-2 text-xs text-ink/50"><ShieldCheck size={15} className="text-gold" /> Sem compromisso</span></div><div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs font-semibold text-ink/60"><MessageCircle size={14} className="text-whatsapp" /> Resposta rápida pelo WhatsApp <span className="text-ink/30">·</span> Sem compromisso</div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-[0.69rem] font-bold uppercase tracking-[0.1em] text-ink/55"><span className="flex items-center gap-2"><Check size={14} className="text-gold" /> Clínica física</span><span className="flex items-center gap-2"><Check size={14} className="text-gold" /> Equipe especializada</span><span className="flex items-center gap-2"><Check size={14} className="text-gold" /> Planejamento digital</span></div></div><div className="hero-visual ppc-hero-visual clinic-hero-gallery animate-fade-in"><div className="clinic-hero-main"><img src="/assets/vita-clinica.jpg" alt="Recepção da clínica Vita Sorriso" /></div><div className="clinic-hero-thumbs"><img src="/assets/vita-fachada-1.jpg" alt="Fachada principal da Vita Sorriso" /><img src="/assets/vita-fachada-2.jpg" alt="Entrada da clínica Vita Sorriso" /></div><div className="hero-note hero-note-top"><span className="note-icon"><Star size={14} fill="currentColor" /></span><span><strong>4,9</strong><small>no Google</small></span></div></div></div></section>

      <section className="ppc-proof"><div className="container grid gap-5 py-6 sm:grid-cols-4"><div><strong>+2.000 sorrisos</strong><span>Experiência em reabilitação oral.</span></div><div><strong>Atendimento individual</strong><span>Seu caso é avaliado com cuidado.</span></div><div><strong>Localização central</strong><span>Rua José Loureiro, 268 — Curitiba.</span></div><a href={googleReviewsUrl} target="_blank" rel="noreferrer" onClick={() => trackConversion("google_reviews_click", "proof")}><strong>Nota 4,9 no Google</strong><span>Mais de 120 avaliações · Ver avaliações</span></a></div></section>

      <section className="video-testimonials" id="depoimentos"><div className="container"><div className="video-testimonials-heading"><div><div className="eyebrow">Histórias reais</div><h2 className="section-title mt-4">Quem viveu o processo, conta.</h2></div><p>Depoimentos em vídeo de pacientes da Vita Sorriso. Cada experiência é individual e o tratamento indicado depende da avaliação clínica.</p></div><div className="video-testimonials-grid"><article className="video-testimonial-card"><div className="video-frame"><video controls playsInline preload="metadata" poster="https://files.manuscdn.com/user_upload_by_module/session_file/310519663950207356/QsKoKLnLHcFSAIpp.jpg"><source src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663950207356/GiNUdXlqRzalJHEa.mp4" type="video/mp4" />Seu navegador não consegue reproduzir este vídeo.</video></div><div className="video-testimonial-caption"><span>Depoimento em vídeo</span><strong>Uma experiência real na Vita Sorriso</strong></div></article><article className="video-testimonial-card"><div className="video-frame"><video controls playsInline preload="metadata" poster="https://files.manuscdn.com/user_upload_by_module/session_file/310519663950207356/EEqVjenEzXJpxKnc.jpg"><source src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663950207356/fUGmFhnaAARLRfHg.mp4" type="video/mp4" />Seu navegador não consegue reproduzir este vídeo.</video></div><div className="video-testimonial-caption"><span>Depoimento em vídeo</span><strong>Histórias reais de quem foi atendido</strong></div></article></div></div></section>

      <section className="ppc-info" id="servicos"><div className="container"><div className="ppc-section-heading"><div className="eyebrow">Atendimento Vita Sorriso</div><h2 className="section-title mt-4">Um primeiro passo claro para o seu caso.</h2><p className="mt-4 max-w-[560px] leading-7 text-ink/60">Na avaliação, você conversa com a equipe, entende as possibilidades do seu caso e recebe orientação para decidir com tranquilidade.</p></div><div className="info-cards mt-10 grid gap-4 md:grid-cols-3"><article><span>01</span><h3>Escuta e avaliação</h3><p>Conversamos sobre suas necessidades, rotina e expectativas antes de indicar qualquer caminho.</p></article><article><span>02</span><h3>Planejamento digital</h3><p>Organizamos as informações do seu caso para explicar as alternativas de forma visual e objetiva.</p></article><article><span>03</span><h3>Acompanhamento próximo</h3><p>Você sabe quais são os próximos passos e conta com a equipe durante todo o processo.</p></article></div><div className="mt-9 text-sm font-semibold text-ink/60">Atendimento presencial no Centro de Curitiba.</div></div></section>


      <section className="ppc-process" id="processo"><div className="container"><div className="ppc-section-heading"><div className="eyebrow">Protocolo completo</div><h2 className="section-title mt-4">Um caminho planejado, etapa por etapa.</h2><p className="mt-4 max-w-[560px] leading-7 text-ink/60">Em casos indicados, o protocolo pode concentrar etapas e permitir dentes fixos provisórios em pouco tempo. Tudo depende da avaliação clínica, dos exames e da estabilidade dos implantes.</p></div><div className="ppc-steps mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4"><div><span>01 · AVALIAÇÃO</span><h3>Entenda seu caso</h3><p>Conversamos sobre saúde, expectativas e rotina para definir o que precisa ser investigado.</p></div><div><span>02 · PLANEJAMENTO</span><h3>Tomografia e plano digital</h3><p>Os exames orientam um planejamento mais seguro e uma explicação visual das possibilidades.</p></div><div><span>03 · IMPLANTES</span><h3>Cirurgia e prótese provisória</h3><p>Quando indicada, a carga imediata pode permitir dentes fixos provisórios no mesmo dia ou em até 24–48 horas.</p></div><div><span>04 · ACOMPANHAMENTO</span><h3>Cuidado até a definitiva</h3><p>A equipe acompanha a adaptação e planeja a prótese definitiva após a cicatrização.</p></div></div><div className="mt-9 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><WhatsAppButton placement="process" /><span className="text-xs text-ink/50">A indicação e o prazo variam conforme cada caso.</span></div></div></section>

      <section className="ppc-faq" id="duvidas"><div className="container grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:gap-16"><div><div className="eyebrow">Dúvidas frequentes</div><h2 className="section-title mt-4">Informação clara para decidir.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question} className="faq-item"><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></div></section>

      <section className="ppc-final" id="localizacao"><div className="container flex flex-col items-center justify-between gap-7 text-center sm:flex-row sm:text-left"><div><div className="eyebrow">Vita Sorriso Implantes</div><h2 className="mt-3 font-display text-3xl text-ink sm:text-4xl">Seu novo sorriso começa com uma conversa.</h2><p className="mt-3 text-sm text-ink/60">Centro de Curitiba · Rua José Loureiro, 268</p><a className="mt-2 inline-flex items-center gap-2 text-sm font-semibold text-ink/70" href="tel:+554196592624" onClick={() => trackConversion("phone_click", "location")}><Phone size={14} /> (41) 9659-2624</a></div><div className="flex flex-col items-center gap-3 sm:items-start"><WhatsAppButton placement="final" /><a href={mapsUrl} target="_blank" rel="noreferrer" onClick={() => trackConversion("maps_click", "location")} className="text-xs font-bold text-ink/60 underline underline-offset-4"><MapPin size={13} className="mr-1 inline" /> Como chegar</a></div></div></section>
    </main>

    <footer className="border-t border-ink/10 bg-paper"><div className="container footer-grid py-9"><div className="footer-brand"><Logo /><p>Implantes dentários com avaliação individual e atendimento especializado em Curitiba.</p></div><div className="footer-links"><strong>Localização</strong><a href={mapsUrl} target="_blank" rel="noreferrer" onClick={() => trackConversion("maps_click", "footer")}>Como chegar</a><span>Rua José Loureiro, 268<br />Centro · Curitiba/PR</span></div></div><div className="container footer-bottom"><p>Vita Sorriso Implantes · Curitiba/PR<br />Resultados, prazos e indicação variam conforme avaliação clínica individual.</p></div></footer>
    <a href={whatsappUrl} target="_blank" rel="noreferrer" className="floating-whatsapp" aria-label="Agendar avaliação pelo WhatsApp" onClick={() => trackConversion("whatsapp_lead", "floating")}><WhatsAppIcon size={31} /></a>
    <div className="mobile-sticky-cta"><WhatsAppButton compact placement="mobile-sticky" /></div>
  </div>;
}
