import { ArrowUpRight, Check, ChevronDown, MapPin, MessageCircle, Phone, ShieldCheck, Star } from "lucide-react";

const whatsappUrl = "https://wa.me/554196592624?text=Ol%C3%A1!%20Vim%20pelo%20site%20da%20Vita%20Sorriso%20e%20gostaria%20de%20agendar%20uma%20avalia%C3%A7%C3%A3o%20para%20implantes%20dent%C3%A1rios%20em%20Curitiba.";
const mapsUrl = "https://www.google.com/maps/dir/?api=1&destination=Rua+Jos%C3%A9+Loureiro%2C+268+-+Centro%2C+Curitiba+-+PR";

function Logo() {
  return <a href="#inicio" className="group inline-flex items-center" aria-label="Vita Sorriso - início"><img src="/manus-storage/vita-logo-enviada_f945e36b.png" alt="Vita Sorriso Implantes" className="brand-logo" /></a>;
}

function WhatsAppButton({ compact = false }: { compact?: boolean }) {
  return <a href={whatsappUrl} target="_blank" rel="noreferrer" className={`whatsapp-button ${compact ? "px-4 py-2.5 text-xs" : "px-5 py-3.5"}`} onClick={() => window.dispatchEvent(new Event("whatsapp_click"))}><MessageCircle size={compact ? 16 : 18} fill="currentColor" /><span>{compact ? "Agendar avaliação" : "Agendar pelo WhatsApp"}</span>{!compact && <ArrowUpRight size={16} />}</a>;
}

const faqs = [
  ["É possível colocar dentes fixos rapidamente?", "Em alguns casos, pode ser indicada uma prótese fixa provisória em curto prazo. A indicação depende da avaliação clínica e da estabilidade dos implantes."],
  ["O tratamento dói?", "O procedimento é realizado com anestesia e os recursos de conforto indicados para cada paciente. Nossa equipe orienta e acompanha o pós-operatório."],
  ["Quanto custa?", "O investimento depende do seu caso, do número de implantes e do tipo de prótese. Você recebe um plano explicado após a avaliação."],
];

export default function Home() {
  return <div className="min-h-screen overflow-x-hidden bg-paper text-ink">
    <div className="topline"><span className="topline-dot" /> Implantes dentários em Curitiba <span className="hidden sm:inline">· Atendimento de segunda a sexta, das 8h às 18h</span></div>
    <header className="sticky top-0 z-40 border-b border-ink/10 bg-paper/90 backdrop-blur-xl"><div className="container flex h-[76px] items-center justify-between gap-6"><Logo /><nav className="hidden items-center gap-8 text-sm font-medium text-ink/65 lg:flex" aria-label="Navegação principal"><a href="#como-funciona" className="nav-link">Como funciona</a><a href="#duvidas" className="nav-link">Dúvidas</a><a href="#localizacao" className="nav-link">Onde estamos</a></nav><WhatsAppButton compact /></div></header>

    <main>
      <section id="inicio" className="hero-section"><div className="hero-orb hero-orb-one" /><div className="container relative grid items-center gap-10 py-14 sm:py-20 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16 lg:py-20"><div className="relative z-10 max-w-[600px] animate-fade-up"><div className="eyebrow"><span className="eyebrow-line" /> Implantes dentários em Curitiba</div><h1 className="mt-7 max-w-[590px] font-display text-[3.3rem] leading-[0.98] tracking-[-0.045em] text-ink sm:text-[4.6rem]">Volte a sorrir com <em className="text-gold">segurança.</em></h1><p className="mt-6 max-w-[510px] text-[1.02rem] leading-8 text-ink/65">Avaliação individual, planejamento digital e uma equipe especializada para cuidar do seu novo sorriso.</p><div className="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><WhatsAppButton /><span className="flex items-center gap-2 text-xs font-medium text-ink/45"><ShieldCheck size={15} className="text-gold" /> Atendimento sem compromisso</span></div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 border-t border-ink/10 pt-5 text-xs font-semibold uppercase tracking-[0.1em] text-ink/50"><span className="flex items-center gap-2"><Check size={15} className="text-gold" /> Planejamento digital</span><span className="flex items-center gap-2"><Check size={15} className="text-gold" /> Clínica física</span><span className="flex items-center gap-2"><Check size={15} className="text-gold" /> Equipe especializada</span></div></div><div className="hero-visual animate-fade-in"><div className="hero-image-wrap"><img src="/manus-storage/clinica-hero_7757a1f7.jpg" alt="Profissional da Vita Sorriso na clínica de implantes em Curitiba" className="hero-image" /><div className="hero-image-shade" /></div><div className="hero-note hero-note-top"><span className="note-icon"><Star size={14} fill="currentColor" /></span><span><strong>4,9</strong><small>no Google</small></span></div><div className="hero-note hero-note-bottom"><span className="note-icon note-icon-dark"><Check size={15} /></span><span><strong>+2.000</strong><small>sorrisos atendidos</small></span></div><div className="hero-caption"><span className="caption-rule" /> Cuidado que começa na escuta</div></div></div></section>

      <section className="trust-strip"><div className="container grid gap-4 py-6 sm:grid-cols-3"><div className="trust-item"><span className="trust-icon"><MapPin size={17} /></span><span><strong>Centro de Curitiba</strong><small>Clínica física</small></span></div><div className="trust-item"><span className="trust-icon"><ShieldCheck size={17} /></span><span><strong>Plano individual</strong><small>Seu caso em primeiro lugar</small></span></div><div className="trust-item"><span className="trust-icon"><Star size={17} /></span><span><strong>4,9 no Google</strong><small>120+ avaliações</small></span></div></div></section>

      <section className="section-space section-tint" id="como-funciona"><div className="container"><div className="max-w-[650px]"><div className="eyebrow"><span className="eyebrow-line" /> Como funciona</div><h2 className="section-title mt-5">Um caminho claro para o seu tratamento.</h2><p className="mt-5 max-w-[560px] leading-7 text-ink/60">O primeiro passo é entender você. Depois, explicamos as opções e acompanhamos cada fase com transparência.</p></div><div className="compact-steps mt-12 grid gap-8 md:grid-cols-3"><div><span className="step-number">01</span><h3 className="mt-4 font-display text-3xl">Avaliação</h3><p className="mt-2 text-sm leading-6 text-ink/60">Conhecemos seu caso e solicitamos os exames necessários.</p></div><div><span className="step-number">02</span><h3 className="mt-4 font-display text-3xl">Planejamento</h3><p className="mt-2 text-sm leading-6 text-ink/60">Você entende o tratamento, o prazo e o investimento.</p></div><div><span className="step-number">03</span><h3 className="mt-4 font-display text-3xl">Acompanhamento</h3><p className="mt-2 text-sm leading-6 text-ink/60">Nossa equipe cuida de cada etapa até sua adaptação.</p></div></div><p className="mt-8 text-xs leading-5 text-ink/45">Prazos e indicação variam conforme as condições clínicas de cada paciente.</p></div></section>

      <section className="dark-section compact-testimonial"><div className="container grid items-center gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><div className="eyebrow eyebrow-light"><span className="eyebrow-line" /> Quem já viveu</div><h2 className="section-title mt-5 text-paper">“Hoje sorrio sem vergonha.”</h2></div><div className="testimonial-quote"><div className="flex gap-1 text-gold"><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /></div><p className="mt-4 max-w-[600px] text-lg leading-8 text-paper/85">“Eu tinha muito medo de dentista, mas fui acolhido em todo o processo. Explicaram cada etapa e hoje sorrio com mais segurança.”</p><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-paper/50">Roberto A. · Paciente Vita Sorriso</p></div></div></section>

      <section className="section-space bg-paper" id="duvidas"><div className="container grid gap-10 lg:grid-cols-[0.65fr_1.35fr] lg:gap-20"><div><div className="eyebrow"><span className="eyebrow-line" /> Dúvidas frequentes</div><h2 className="section-title mt-5">Respostas diretas para você decidir com tranquilidade.</h2><a href={whatsappUrl} target="_blank" rel="noreferrer" className="text-link mt-7 inline-flex">Falar com a equipe <ArrowUpRight size={16} /></a></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question} className="faq-item"><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></div></section>

      <section className="location-section compact-location" id="localizacao"><div className="container grid items-center gap-9 lg:grid-cols-[1.1fr_0.9fr]"><div><div className="eyebrow eyebrow-light"><span className="eyebrow-line" /> Estamos em Curitiba</div><h2 className="section-title mt-5 text-paper">Uma clínica feita para você se sentir à vontade.</h2><p className="mt-4 max-w-[510px] leading-7 text-paper/65">Rua José Loureiro, 268 — Centro, Curitiba — PR.</p><div className="mt-7 flex flex-col items-start gap-3 sm:flex-row"><WhatsAppButton /><a href={mapsUrl} target="_blank" rel="noreferrer" className="outline-button"><MapPin size={16} /> Como chegar</a></div></div><div className="clinic-gallery"><img src="/manus-storage/clinica-recepcao_dc727bef.jpg" alt="Recepção da clínica Vita Sorriso" className="clinic-gallery-main" /><img src="/manus-storage/clinica-fachada-1_83ebbb19.jpg" alt="Fachada da clínica Vita Sorriso" className="clinic-gallery-small" /><div className="location-label"><strong>Vita Sorriso Implantes</strong><span>Centro · Curitiba/PR</span></div></div></div></section>
    </main>

    <footer className="border-t border-ink/10 bg-paper"><div className="container flex flex-col gap-5 py-7 text-sm text-ink/50 sm:flex-row sm:items-center sm:justify-between"><Logo /><div className="flex flex-col gap-2 text-left sm:items-end"><a href="tel:+554196592624" className="flex items-center gap-2 hover:text-ink"><Phone size={14} /> (41) 9659-2624</a><span>Vita Sorriso Implantes · Curitiba/PR</span></div></div><div className="container border-t border-ink/10 py-4 text-[0.68rem] leading-5 text-ink/40">Resultados, prazos e indicação variam conforme cada caso e devem ser definidos em avaliação clínica.</div></footer>
    <a href={whatsappUrl} target="_blank" rel="noreferrer" className="floating-whatsapp floating-whatsapp-labeled" aria-label="Falar com a Vita Sorriso pelo WhatsApp"><MessageCircle size={21} fill="currentColor" /><span>WhatsApp</span></a>
  </div>;
}
